
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/home/murilo/slas/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface SitePreferences {
			/**
			* Redirect URI - SLAS Login

				Redirect URI used for SLAS Login
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#5) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#45)
			*/
			redirectURI_SLAS: string | null;

			/**
			* Restore Session Attributes

				When using plugin_slas, session attributes will not be restored after a successful OCAPI session bridge. Enable this site preference to make an additional http request to a controller which will restore the original session.custom and session.privacy attributes. Please ensure you set your storefront credentials in the "controller.internal.cred" service credential; these credentials are required in all (SIG and PIG) environments.
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#12) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#49)
			*/
			restoreSessionAttributes_SLAS: boolean | null;

			/**
			* Always Save Refresh token
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#20) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#46)
			*/
			saveRefreshToken_Always: boolean | null;

			/**
			* SFCC OCAPI Session Bridge URI

				Request URI used for OCAPI Session - SLAS
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#27) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#47)
			*/
			ocapiSessionBridgeURI_SLAS: string | null;

			/**
			* Client IP Header Name

				The header name used to passthrough the client IP. This must match the Client IP Header Name set in Customer CDN settings in Business Manager.
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#34) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#48)
			*/
			clientIPHeaderName: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Redirect URI - SLAS Login

				Redirect URI used for SLAS Login
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#5) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#45)
			*/
			(name: 'redirectURI_SLAS'): string | null;
			
			/**
			* Restore Session Attributes

				When using plugin_slas, session attributes will not be restored after a successful OCAPI session bridge. Enable this site preference to make an additional http request to a controller which will restore the original session.custom and session.privacy attributes. Please ensure you set your storefront credentials in the "controller.internal.cred" service credential; these credentials are required in all (SIG and PIG) environments.
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#12) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#49)
			*/
			(name: 'restoreSessionAttributes_SLAS'): boolean | null;
			
			/**
			* Always Save Refresh token
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#20) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#46)
			*/
			(name: 'saveRefreshToken_Always'): boolean | null;
			
			/**
			* SFCC OCAPI Session Bridge URI

				Request URI used for OCAPI Session - SLAS
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#27) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#47)
			*/
			(name: 'ocapiSessionBridgeURI_SLAS'): string | null;
			
			/**
			* Client IP Header Name

				The header name used to passthrough the client IP. This must match the Client IP Header Name set in Customer CDN settings in Business Manager.
			* @group SLAS Plugin - SLAS Plugin Configurations
			* @source [attribute](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#34) | [group](file:/home/murilo/slas/meta/system-objecttype-extensions.xml#48)
			*/
			(name: 'clientIPHeaderName'): string | null;
			
	}
}